#!/usr/bin/env python3
"""Write hashed participant identifiers for the main wiki's pre-commit hook.

Run from the root of the restricted vault:

    python3 scripts/build-denylist.py

Reads ``participants.csv`` (full_name, email, phone columns) and
``denylist-extra.txt`` (one identifier per line), and writes SHA-256 hashes of
their normalized forms to ``~/.config/llm-wiki/denylist``. No plaintext
identifier is written anywhere.

Standalone on purpose: the restricted vault does not depend on the llm-wiki
package. The normalization below must stay identical to
``llm_wiki.hooks.denylist``; the tools repo's test suite checks this.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import os
import re
import sys
import unicodedata
from pathlib import Path

DEFAULT_OUT = Path("~/.config/llm-wiki/denylist").expanduser()
MAX_NGRAM = 4

_TOKEN = re.compile(r"[^\W_]+(?:['’-][^\W_]+)*")


def normalize_name(s: str) -> str:
    s = unicodedata.normalize("NFKD", unicodedata.normalize("NFKC", s).casefold())
    s = "".join(c for c in s if not unicodedata.combining(c))
    return " ".join(_TOKEN.findall(s))


def normalize_email(s: str) -> str:
    return s.strip().lower()


def normalize_phone(s: str) -> str:
    return re.sub(r"\D", "", s)[-10:]


def digest(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def identifier_hash(raw: str) -> str | None:
    """Hash one identifier, classified as email, phone, or name."""
    raw = raw.strip()
    if not raw:
        return None
    if "@" in raw:
        return digest(normalize_email(raw))
    digits = re.sub(r"\D", "", raw)
    if len(digits) >= 10 and not re.search(r"[^\d\s().+-]", raw):
        return digest(normalize_phone(raw))
    name = normalize_name(raw)
    if len(name.split()) > MAX_NGRAM:
        print(f"warning: an identifier has more than {MAX_NGRAM} words and will never match", file=sys.stderr)
    return digest(name) if name else None


def collect(vault: Path) -> set[str]:
    hashes: set[str] = set()
    participants = vault / "participants.csv"
    if participants.exists():
        with participants.open(newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                for column in ("full_name", "email", "phone"):
                    h = identifier_hash(row.get(column) or "")
                    if h:
                        hashes.add(h)
    extra = vault / "denylist-extra.txt"
    if extra.exists():
        for line in extra.read_text(encoding="utf-8").splitlines():
            if not line.lstrip().startswith("#"):
                h = identifier_hash(line)
                if h:
                    hashes.add(h)
    return hashes


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--vault", type=Path, default=Path.cwd())
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    if not (args.vault / "participants.csv").exists():
        print(f"error: no participants.csv in {args.vault}; run from the vault root", file=sys.stderr)
        return 1
    hashes = collect(args.vault)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.out.with_suffix(".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        f.write("# llm-wiki participant denylist: SHA-256 of normalized identifiers.\n")
        f.write("# Generated by the restricted vault's build-denylist.py. Do not edit or commit.\n")
        for h in sorted(hashes):
            f.write(h + "\n")
    os.chmod(tmp, 0o600)
    tmp.replace(args.out)
    print(f"wrote {len(hashes)} hashed identifiers to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
