"""wiki-index: regenerate the per-directory catalogs and the router's catalog list.

Each ``wiki/<type>/index.md`` is rewritten in full: every page in the
directory, one line each (link, one-line summary, projects, last updated).
The router ``index.md`` is hand-curated; only the block between the
``wiki-index:catalogs`` markers is regenerated, and the router is refused if it
would exceed its 300-line cap.
"""

from __future__ import annotations

import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from llm_wiki import frontmatter
from llm_wiki.cli import parser, run
from llm_wiki.errors import WikiError
from llm_wiki.text import first_sentence
from llm_wiki.vault import CATALOG, Vault, catalog_title

ROUTER = "index.md"
ROUTER_CAP = 300
BEGIN = "<!-- wiki-index:catalogs -->"
END = "<!-- /wiki-index:catalogs -->"
_WIKILINK = re.compile(r"!?\[\[([^\[\]|#]*)(?:#[^\[\]|]*)?(?:\|([^\[\]]*))?\]\]")


def plain(text: str) -> str:
    """Markdown → text for one-line summaries: links to their labels, emphasis dropped."""
    text = _WIKILINK.sub(lambda m: m.group(2) or m.group(1).rsplit("/", 1)[-1], text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<!--.*?-->", "", text)
    return re.sub(r"(\*\*|__|`)", "", text).strip()


def _section(body: str, heading: str) -> str | None:
    m = re.search(rf"^##\s+{re.escape(heading)}\s*$(.*?)(?=^#{{1,2}}\s|\Z)", body, flags=re.MULTILINE | re.DOTALL)
    return m.group(1) if m else None


def first_paragraph(body: str) -> str:
    para: list[str] = []
    fence = False
    for line in body.split("\n"):
        s = line.strip()
        if s.startswith(("```", "~~~")):
            fence = not fence
            continue
        if fence:
            continue
        if not s:
            if para:
                break
            continue
        if s.startswith(("#", "- ", "* ", "> ", "|", "<!--", "---")) or re.match(r"\d+\.\s", s):
            if para:
                break
            continue
        para.append(s)
    return " ".join(para)


def summary(meta: dict[str, Any], body: str) -> str:
    if meta.get("summary"):
        return first_sentence(plain(str(meta["summary"])))
    text = None
    if meta.get("type") == "source":
        text = _section(body, "Gist")
    return first_sentence(plain(first_paragraph(text if text is not None else body)))


def _label(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("|", "-").replace("[", "(").replace("]", ")")).strip()


def catalog_line(vault: Vault, path: Path, warnings: list[str]) -> str:
    pid = vault.rel(path).removesuffix(".md")
    try:
        meta, body = frontmatter.read(path)
    except WikiError as exc:
        warnings.append(str(exc))
        return f"- [[{pid}|{_label(path.stem)}]] — (invalid frontmatter)"
    title = _label(str(meta.get("title") or path.stem))
    marks = []
    if meta.get("stub") is True:
        marks.append("stub")
    if meta.get("status") in ("superseded", "retracted", "retired", "withdrawn", "dissolved"):
        marks.append(str(meta["status"]))
    parts = [f"- [[{pid}|{title}]]" + (f" ({', '.join(marks)})" if marks else "")]
    if text := summary(meta, body):
        parts.append(f" — {text}")
    tail = []
    if projects := frontmatter.as_list(meta.get("projects")):
        tail.append(", ".join(projects))
    if updated := frontmatter.as_date(meta.get("updated")):
        tail.append(f"updated {updated}")
    if tail:
        parts.append(" · " + " · ".join(tail))
    return "".join(parts)


def catalog(vault: Vault, directory: str, warnings: list[str]) -> tuple[str, int]:
    base = vault.wiki / directory
    pages = sorted(
        (p for p in base.rglob("*.md") if not (p.parent == base and p.name == CATALOG)
         and not any(part.startswith(".") for part in p.relative_to(base).parts)),
        key=lambda p: p.relative_to(base).as_posix().lower(),
    )
    lines = [catalog_line(vault, p, warnings) for p in pages]
    noun = "page" if len(lines) == 1 else "pages"
    head = [
        f"# {catalog_title(directory)}",
        "",
        "Catalog regenerated by `wiki-index`. Do not edit by hand.",
        "",
        f"{len(lines)} {noun}.",
    ]
    return "\n".join([*head, *([""] + lines if lines else [])]) + "\n", len(lines)


def router_block(counts: dict[str, int]) -> str:
    lines = [f"- [[wiki/{d}/index|{catalog_title(d)}]] ({n})" for d, n in counts.items()]
    return "\n".join([BEGIN, *lines, END])


def render_router(text: str, counts: dict[str, int]) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        raise WikiError(
            f"{ROUTER} has no catalog block; put the catalog list between {BEGIN} and {END} lines"
        )
    return text[:start] + router_block(counts) + text[end + len(END):]


def build(vault: Vault) -> dict[str, Any]:
    warnings: list[str] = []
    counts: dict[str, int] = {}
    changed: list[str] = []
    for d in vault.wiki_dirs():
        if not (vault.wiki / d).is_dir():
            continue
        text, n = catalog(vault, d, warnings)
        counts[d] = n
        target = vault.wiki / d / CATALOG
        if vault.write_text(target, text):
            changed.append(vault.rel(target))

    router = vault.root / ROUTER
    try:
        current = router.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise WikiError(f"{ROUTER} not found at the repository root") from None
    new = render_router(current, counts)
    length = new.count("\n") + (not new.endswith("\n"))
    if length > ROUTER_CAP:
        raise WikiError(
            f"{ROUTER} would be {length} lines, over its {ROUTER_CAP}-line cap; move detail into catalogs "
            f"(catalogs were updated: {len(changed)} changed)"
        )
    if vault.write_text(router, new):
        changed.append(ROUTER)
    return {"counts": counts, "changed": changed, "warnings": warnings, "router_lines": length}


def main(argv: Sequence[str] | None = None) -> int:
    p = parser("wiki-index", "Regenerate per-directory catalogs and the router's catalog list.")
    p.parse_args(argv)
    vault = Vault.find()
    result = build(vault)
    for w in result["warnings"]:
        print(f"warning: {w}", file=sys.stderr)
    total = sum(result["counts"].values())
    print(f"{total} pages in {len(result['counts'])} catalogs; router {result['router_lines']}/{ROUTER_CAP} lines")
    for path in result["changed"]:
        print(f"  updated {path}")
    return 0


def cli() -> int:
    return run(main)
